apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"
  MONGO_CONNECTION_STRING: "mongodb://root:example@example-mongodb-svc.dev.svc.cluster.local:27017/?replicaSet=example-mongodb"
