apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-database-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nnikolovskii/dotnet_finki_rasporedi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__DefaultConnection
          value: Server=mysql;Port=3306;Database=finki_rasporedi;User=admin;Password=ogan123;
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"