apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nnikolovskii/vinozito-v1:latest
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: ASPNETCORE_ENVIRONMENT
          - name: ASPNETCORE_URLS
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: ASPNETCORE_URLS
          - name: ConnectionStrings__MongoDb
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: MONGO_CONNECTION_STRING
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"