apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: my-database-namespace
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None  # Headless service for StatefulSet